using Microsoft.VisualStudio.TestTools.UnitTesting;
using VintriCore.Controllers;
using System;
using System.Collections.Generic;
using System.Text;
using System.Net.Http;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;

namespace VintriCore.Controllers.Tests
{
    [TestClass()]
    public class BeerListControllerTests
    {
        [TestMethod()]
        public void GetAsyncTest()
        {
//            HttpClient stockFeed =
//            new HttpClient.Fakes.// Generated by Fakes.


//            var stub = new StubIhht();

            //            BeerListController beerListController = new BeerListController(httpClientFactoryMock, );




            Assert.Fail();
        }
    }
}

namespace VintriCoreTests.Controllers
{
    class BeerListControllerTests
    {
    }
}
